006. Blog Website/main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path('',views.index,name='index'),
    path('blog/<int:pk>', views.blog,name="getBlog"),
    path('author/<int:pk>', views.author,name="getAuth"),
    
    path('new-blog',views.createBlog, name= "createBlog")
    
]

006. Blog Website/main/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
    name = models.CharField(max_length=256)
    def __str__(self):
        return self.name
class Blog(models.Model):
    title = models.CharField(max_length=256)
    createdAt = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    authors =  models.ManyToManyField('Author')
    def __str__(self):
        return self.title

006. Blog Website/main/views.py
from django.shortcuts import render,get_object_or_404
from main import models
from django.http import(
    Http404
)
# Create your views here.
def index(request):
    # Queries are executed lazily
    latest_blogs =models.Blog.objects.all().order_by('-createdAt')[:10]
    
    context = {
        'latest_blogs' : latest_blogs
    }
    return render(request,'main/index.html',context)

def blog(request,pk):
    # try:
    #     blog = models.Blog.objects.get(pk = pk)
    # except:
    #     raise Http404
    blog = get_object_or_404(models.Blog,pk=pk)
    context = {
        'cBlog' : blog
    }
    return render(request,'main/blog.html',context)

def author(request,pk):
    # try:
    #     blog = models.Blog.objects.get(pk = pk)
    # except:
    #     raise Http404
    auth = get_object_or_404(models.Author,pk=pk)
    context = {
        'cAuth' : auth
    }
    return render(request,'main/author.html',context)

def createBlog(request):
    
    authors = models.Author.objects.all()
    context={
        'authors': authors 
    }
    
    if(request.method == "POST"):
        blogData = {
            'title': request.POST['title'],
            'content' : request.POST['content']
        }
        blog = models.Blog.objects.create(**blogData)
        auth = models.Author.objects.filter(pk = request.POST['author'])
        blog.authors.set(auth)
        
        context["success"] = True
    
    
    return render(request, 'main/createBlog.html',context)

006. Blog Website/templates/main/author.html
{% extends 'main/base.html' %} {% block body %}
<h1>Name : {{cAuth.name}}</h1>
<h4>Blogs Written :</h4>
<ul>
    {% for b in cAuth.blog_set.all %}
    <li>
        <a href="{% url 'getBlog' b.pk %}">{{b}}</a>
    </li>
    {%endfor%}
</ul>
{% endblock %}

006. Blog Website/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Blogger</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}" />
    <script src="{% static 'js/materialize.min.js' %}"></script>
    {% block head %}{% endblock %}
</head>

<body>
    {% block body %} {% endblock %}
</body>

</html>

006. Blog Website/templates/main/blog.html
{% extends 'main/base.html' %} {% block body %}
<h1>{{cBlog.title}}</h1>
<h3>Created At : {{cBlog.createdAt}}</h3>
<h4>
    Written By : {% for a in cBlog.authors.all %}
    <a href="{% url 'getAuth' a.id %}">{{a}}</a> &nbsp; {%endfor%}
</h4>

<p>{{cBlog.content}}</p>
{% endblock %}

006. Blog Website/templates/main/createBlog.html
{% extends 'main/base.html' %} {% block body %}
<div class="container center-align">
    <h1 class="center-align">Create a new Blog Right here!</h1>
    {% if success %} Form Submitted Successfully! {%endif%}
    <div class="row">
        <form method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="input-field col s12">
                    <input type="text" name="title" id="title" placeholder="Enter Title Here" />
                    <label for="first_name">Enter Title of the Blog Here: </label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <select name="author">
            {% for a in authors %}
            <option value="{{a.id}}">{{a}}</option>
            {% endfor %}
          </select>
                    <label>Choose Author</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <textarea name="content" id="content" placeholder="Enter Content of the Blog Here" cols="30" class="materialize-textarea"></textarea>
                    <label for="content">Enter the Conent of your Blog Here : </label>
                </div>
            </div>

            <button class="btn waves-effect waves-light" type="submit">
        PUBLISH BLOG
        <i class="material-icons right">send</i>
      </button>
            <br />
            <br />
            <button class="btn waves-effect waves-light #c0ca33 lime darken-1" type="reset">
        RESET BLOG FORM
        <i class="material-icons right">autorenew</i>
      </button>
        </form>
    </div>
    <!-- {% if success %} Form Submitted Successfully! {%endif%}

    <form method="POST">
        {% csrf_token %}
        <input type="text" name="title" id="title" placeholder="Enter Title Here" />
        <textarea name="content" id="content" placeholder="Enter Content of the Blog Here" cols="30"></textarea>
        <select name="author">
      {% for a in authors %}
      <option value="{{a.id}}">{{a}}</option>
      {%endfor%}
    </select>

        <button type="submit">Publish Blog</button>
        <button type="reset">Reset Blog Form</button>
    </form> -->
</div>
{% endblock %} {% block head %}
<script>
    document.addEventListener("DOMContentLoaded", function() {
        var elems = document.querySelectorAll("select");
        var instances = M.FormSelect.init(elems);
    });
</script>
{%endblock%}

006. Blog Website/templates/main/index.html
{% extends 'main/base.html' %} {% block body %}
<div class="container">
    <h1 class="center-align">Welcome to the Blogger</h1>
    <h5 class="center-align">Top 10 Blogs</h5>
    <ul>
        {% for b in latest_blogs %}
        <li>
            <a href="{% url 'getBlog' b.pk %}">{{b}}</a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}