008. Generic Views/Student_Management/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]

008. Generic Views/main/urls.py
from django.urls import path
from main import views
urlpatterns = [
    path('',views.Index.as_view(),name="index"),
    path('college/<int:pk>',views.CollegeDetail.as_view(),name="getCollege"),
    path('college/',views.CollegeList.as_view(),name="allCollege"),
    path('createCollege', views.CollegeCreate.as_view(),name="create_college"),
    path('student/<int:pk>',views.StudentDetail.as_view(),name="getstudent"),
    path('student/',views.StudentList.as_view(),name="allstudent"),
    path('createStudent', views.StudentCreate.as_view(),name="create_student"),
    path('updateCollege/<int:pk>',views.UpdateCollege.as_view(),name='updateCollege'),
    path('deleteCollege/<int:pk>',views.DeleteCollege.as_view(),name="deleteCollege"),
    path('updateStudent/<int:pk>',views.UpdateStudent.as_view(),name='updateStudent'),
    path('deleteStudent/<int:pk>',views.DeleteStudent.as_view(),name="deleteStudent")
]

008. Generic Views/main/models.py
from django.db import models

# Create your models here.

class Student(models.Model):
    name = models.CharField(max_length=256)
    rollNo = models.IntegerField(unique=True)
    college = models.ForeignKey('College',on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class College(models.Model):
    name = models.CharField(max_length=256)
    def __str__(self):
        return self.name

008. Generic Views/main/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View
from main import models

from django.views.generic import(
    DetailView, 
    ListView,
    CreateView,
    UpdateView,
    DeleteView
)
# Create your views here.

class Index(View):
    def get(self,request):
        return HttpResponse("GET Request")
    
    def post(self,request):
        return HttpResponse("POST Request")

# Detail View
# List View
# Create View
# Update View
# Delete View
  
class CollegeDetail(DetailView):
    # Meta data
    model = models.College
    template_name = 'main/college_detail.html'

class CollegeList(ListView):
    model = models.College
    template_name = 'main/college_list.html'
    context_object_name = 'allColleges'

class CollegeCreate(CreateView):
    model = models.College
    template_name = 'main/cCollege.html'
    fields = '__all__'
    success_url = '/college'

class StudentDetail(DetailView):
    # Meta data
    model = models.Student
    template_name = 'main/student_detail.html'

class StudentList(ListView):
    model = models.Student
    template_name = 'main/student_list.html'
    context_object_name = 'allStudents'

class StudentCreate(CreateView):
    model = models.Student
    template_name = 'main/cstudent.html'
    fields = '__all__'
    success_url = '/student'

class UpdateCollege(UpdateView):
    model = models.College
    template_name = 'main/cCollege.html'
    fields = '__all__'
    success_url = '/college'
    
class DeleteCollege(DeleteView):
    model = models.College
    template_name = 'main/confirm.html'
    success_url = '/college'
    

class UpdateStudent(UpdateView):
    model = models.Student
    template_name = 'main/cstudent.html'
    fields = '__all__'
    success_url = '/student'
    
class DeleteStudent(DeleteView):
    model = models.Student
    template_name = 'main/confirm.html'
    success_url = '/student'

008. Generic Views/templates/main/cCollege.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
</head>

<body>
    <h1>Add New College</h1>
    <form action="" method="POST">
        {% csrf_token %} {{form}}
        <button type="submit">SUBMIT</button>
    </form>
</body>

</html>

008. Generic Views/templates/main/college_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Particular</title>
</head>

<body>
    <h1>College Detail Page View</h1>
    Name : {{object.name}}<br /> Students:
    <ul>
        {%for s in object.student_set.all %}
        <li>{{s.name}}</li>
        {%endfor%}
    </ul>
</body>

</html>

008. Generic Views/templates/main/college_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>All</title>
</head>

<body>
    <ul>
        {% for c in allColleges %}
        <li><a href="{% url 'getCollege' c.pk %}"> {{c.name}}</a></li>
        {%endfor%}
    </ul>
</body>

</html>

008. Generic Views/templates/main/confirm.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
</head>

<body>
    <form action="" method="POST">
        {% csrf_token %}
        <label for="">Do you really want to delete?</label>
        <button>DON'T DELETE</button>
        <button type="submit">DELETE</button>
    </form>
</body>

</html>

008. Generic Views/templates/main/cstudent.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
</head>

<body>
    <h1>Add Student</h1>
    <form action="" method="POST">
        {% csrf_token %} {{form}}
        <button type="submit">SUBMIT</button>
    </form>
</body>

</html>

008. Generic Views/templates/main/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Student Management</title>
</head>

<body></body>

</html>

008. Generic Views/templates/main/student_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
</head>

<body>
    <h1>Student Data</h1>
    RollNo : {{object.rollNo}} <br /> Name : {{object.name}} <br /> College : {{object.college}}
</body>

</html>

008. Generic Views/templates/main/student_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
</head>

<body>
    <h1>All Students</h1>

    <ul>
        {% for s in allStudents %}
        <li>
            <a href="{% url 'getstudent' s.pk %}">{{s.name}}</a>
        </li>
        {% endfor %}
    </ul>
</body>

</html>